services:
    postgres:
        image: postgres:16
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: urlshortener
        volumes:
            - pgdata:/var/lib/postgresql/data
    backend:
        build:
            context: .
            dockerfile: backend/Dockerfile
        ports:
            - '4200:4200'
        environment:
            - DATABASE_URL=postgresql://user:password@postgres:5432/urlshortener?schema=public
        depends_on:
            - postgres
    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        ports:
            - '5173:80'
        depends_on:
            - backend

volumes:
    pgdata:
